# Generated by Django 4.0.4 on 2022-05-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='gender',
            new_name='language1',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='language',
            new_name='language2',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='location',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobp.teacher'),
        ),
    ]
