# Generated by Django 4.0.4 on 2022-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0003_alter_teacher_about_me_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
