# Generated by Django 4.0.4 on 2022-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0005_alter_teacher_language2_alter_teacher_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language1',
            field=models.CharField(choices=[('AJ', 'Anglicky jazyk'), ('NJ', 'Nemecky jazyk'), ('IT', 'Nemecky jazyk'), ('RJ', 'Rusky jazyk'), ('FJ', 'Francouzsky jazyk'), ('SJ', 'Spanelsky jazyk')], max_length=50),
        ),
    ]
