# Generated by Django 4.0.4 on 2022-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0006_alter_teacher_language1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language2',
            field=models.CharField(blank=True, choices=[('AJ', 'Anglicky jazyk'), ('NJ', 'Nemecky jazyk'), ('IT', 'Nemecky jazyk'), ('RJ', 'Rusky jazyk'), ('FJ', 'Francouzsky jazyk'), ('SJ', 'Spanelsky jazyk')], max_length=50, null=True),
        ),
    ]
