# Generated by Django 4.0.4 on 2022-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0009_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
