# Generated by Django 4.0.4 on 2022-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0010_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(choices=[('AJ', 'Anglicky jazyk'), ('NJ', 'Nemecky jazyk'), ('IT', 'Italsky jazyk'), ('RJ', 'Rusky jazyk'), ('FJ', 'Francouzsky jazyk'), ('SJ', 'Spanelsky jazyk')], max_length=50),
        ),
    ]
