# Generated by Django 4.0.4 on 2022-05-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobp', '0013_alter_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='price',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('about_me', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobp.teacher')),
            ],
        ),
    ]
